### ISSUE TITLE
client.Connect code not return libmqtt.CtrlConn, but zero

### ISSUE THREAD

**Issue by skillcoder** [goiiot/libmqtt#11]
I'm switch from paho.mqtt.golang
But, i cant even connect to mosquitto server with this code:
~~~ go
func mqttConnect(host string, port uint16, name string) {
  mqtturi := fmt.Sprintf("%s:%d", host, port);
  mqttClient, err := libmqtt.NewClient(
    libmqtt.WithServer(mqtturi),
    libmqtt.WithBuf(512, 512), // send, recv
    libmqtt.WithClientID(name),
    libmqtt.WithDialTimeout(2), // Connection timeout
    libmqtt.WithLog(libmqtt.Verbose), // Silent/Verbose/Debug/Info/Warning/Error
  )
  if err != nil {
    // handle client creation error
    log.Panic("mqttClient creation ERR:", err)
  }

  mqttClient.HandlePub(PubHandler)
  mqttClient.HandleSub(SubHandler)
  mqttClient.HandleUnSub(UnSubHandler)
  mqttClient.HandleNet(NetHandler)
  mqttClient.HandlePersist(PersistHandler)

  mqttClient.Connect(func(server string, code byte, err error) {
    if err != nil {
        log.Panic("mqttConnect ERR:", err)
    }

    if code != libmqtt.CtrlConn {
        // server rejected or in error
        log.Panicf("mqttConnect server CODE: %d", code)
    }

    espInit()
  })
}
~~~

Verbose log:
[LIBMQTT] D 2018/09/21 02:36:56 CLI registered pub handler
[LIBMQTT] D 2018/09/21 02:36:56 CLI registered sub handler
[LIBMQTT] D 2018/09/21 02:36:56 CLI registered unsub handler
[LIBMQTT] D 2018/09/21 02:36:56 CLI registered net handler
[LIBMQTT] D 2018/09/21 02:36:56 CLI registered persist handler
[LIBMQTT] D 2018/09/21 02:36:56 CLI connect to server, handler = 0x845fb0
[LIBMQTT] V 2018/09/21 02:36:56 NET start send handle for server =  127.0.0.1:1883
[LIBMQTT] I 2018/09/21 02:36:56 CLI connected to server = 127.0.0.1:1883
[LIBMQTT] D 2018/09/21 02:36:56 NET start keepalive
PANI[0000] mqttConnect server CODE: 0
Panic cuz
```
  mqttClient.Connect(func(server string, code byte, err error) {
    if code != libmqtt.CtrlConn {
```

How can I know why code == 0, but must be 1, cuz libmqtt.CtrlConn = 1
If i ignore this i get [signal SIGSEGV: segmentation violation... 
on  `mqttClient.Subscribe(&libmqtt.Topic{Name: Name})`

**Comment by jeffreystoke** [comment]
@skillcoder oh, it seems a document issue, in this package a `CtrlXXX` means a packet type, not the response code, see [Packet type](https://github.com/goiiot/libmqtt/blob/66e815f75aeb9e2a3b37c747cec68fcd3d532069/libmqtt.go#L78)


And the response code is `CodeXXX`, see [Response code](https://github.com/goiiot/libmqtt/blob/66e815f75aeb9e2a3b37c747cec68fcd3d532069/libmqtt.go#L128)

Really sorry for this issue, I am working on it, or you can fire a pull request to fix it, have a nice day!

**Comment by skillcoder** [comment]
I just use this code, after code in first message.
~~~ go
var mqttClient libmqtt.Client

func mqttSubscribe(Name string) {
  mqttClient.Subscribe(&libmqtt.Topic{Name: Name})
}

~~~

**Comment by skillcoder** [comment]
Why u dont fix this in readme ?
`    if code != libmqtt.CtrlConn {`

**Comment by jeffreystoke** [comment]
Glad to see your problem solved, and thank you for your contribution to this project.

Have a nice day :)
