### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by mingan** [goiiot/libmqtt#16]
I searched for a way to connect to a broker over TLS.

The readme doesn't talk about it. There are options like `WithTLS` but those are for client certificates. Documentation for [`WithServer`](https://godoc.org/github.com/goiiot/libmqtt#WithServer) mentions that only TCP is supported.

Is there an officially supported way to connect to a broker over TLS (with server certificate)? The only way I could figure out is by poking in the implementation + documentation of the [TLS package](https://golang.org/pkg/crypto/tls/#Dial):

```go
client, err := libmqtt.NewClient(
    libmqtt.WithCustomTLS(&tls.Config{}),
    // ...
)
```

Is this correct/expected or is there a better way?

**Comment by jeffreystoke** [comment]
Hi @mingan , you're right, currently we don't have any convenient way to use a server certificate, feel free to talk about this if you have any suggestion.

Have a nice day :)

**Comment by mingan** [comment]
As I mentioned, it is possible to force the library to connect over TLS but the way is far from intuitive and comes down to [this block](https://github.com/goiiot/libmqtt/blob/master/client.go#L531..L559), specifically getting into the first branch.

If I consider a user of this library, the most natural way to connect with server certificate would be to write `libmqtt.WithServer("mqtts://mqtt.broker.com")`, i.e. include the scheme and then switch on it. The downsides I can see are:

- it's possible to enter multiple servers, so technically it might be possible to enter one with `mqtt` scheme, one with `mqtts`, what to do then?
- it's not backwards compatible by itself - could be taken care of by defaulting to plain TCP when the scheme is missing but I have no idea if it affects the C and Java code in any way

For clarity, I suggest to rename the `WithTLS` and `WithTLSReader` to `WithClientTLSCertificate` and `WIthClientTLSCertificateReader`.

**Comment by jeffreystoke** [comment]
@mingan good point, at the time I implementing this library, I didn't intend to use tls as a method for server verification only, but for bidirectional verification, maybe we just need something like `WithSecureServer("localhost:1883")` if we just want to verify server certificate, and apply tls config to plain tcp server for bidirectional verification?

**Comment by mingan** [comment]
You're fast!

**Comment by jeffreystoke** [comment]
Closing since #17 has been merged, feel free to reopen
