### ISSUE TITLE
Test with go-fuzz

### ISSUE THREAD

**Issue by jeffreystoke** [goiiot/libmqtt#2]
We will use go-fuzz to test this project. Any other fuzzy test tool?

**Comment by dgryski** [comment]
go-fuzz is probably sufficient for fuzzing the packet parsing code.  You could optionally use something like https://github.com/mschoch/smat or your own custom code to test protocol-level edge cases (for example, any invalid transitions for the mqtt state machine.)

**Comment by jeffreystoke** [comment]
@dgryski thanks for these suggestions, very helpful to me, I am a newbie in lib maintain and testing area.

**Comment by jeffreystoke** [comment]
Passed fuzzy test now.
