### ISSUE TITLE
回调阻塞产生大量协程

### ISSUE THREAD

**Issue by huskar-t** [goiiot/libmqtt#34]
client_async.go 内 handleTopicMsg 方法调用 addWorker 方法直接启动 goroutine 来执行回调。在回调执行时间比下一条消息接收时间慢时会产生大量的 goroutine 。是否考虑使用 goroutine pool 的方式限制 goroutine 数量？

**Comment by jeffreystoke** [comment]
迟到的回复，非常抱歉！

goroutine pool是个好主意，之前就有过这样的担心，主要是内存压力，尤其是go1.14换了linux内存回收策略之后，至于cpu，感觉goroutine上万并不是什么问题。

另外你有在这方面遇到过性能问题吗，如果能提供测试结果就更好了，要是确实能提升性能的话可以在1.0中加入。

近来都没什么时间维护，希望可以谅解。

**Comment by huskar-t** [comment]
我们在实测中回调使用redis处理速度慢于消息到来速度导致无限产生协程，最终panic

**Comment by jeffreystoke** [comment]
如果是这种情况的话我觉得可能的解决方案会有（任选）

- 尝试使用 redis pipeline
- 缓存消息到内存再存入redis （让goroutine尽早结束）
- mqtt 消息分片，改良mqtt topic设计，实现分布式部署

因为我的考虑是既然是消息太多，那么如果处理不及时会导致socket buf满了，进而可能会导致tcp窗口变小，然后导致消息接收变慢产生延迟，不知你们是否会有这样的担心。

当然可以在libmqtt中加入缓存机制，但我目前还是觉得这和应用程序有关，协议库应该尽快传达数据，你怎么看？

**Comment by huskar-t** [comment]
产生的主要问题是我们在回调中没有使用协程产生阻塞，并不是redis的改良之类的，我的想法是回调已经在一个协程中我没必要再启动一个协程，比如一些必须使用同步的场景就会出现上面的情况，我说的redis只是举一个例子

**Comment by huskar-t** [comment]
因为我无法控制回调函数所在的goroutine,作为使用者只能再启动一个goroutine来跳出回调函数的goroutine

**Comment by jeffreystoke** [comment]
> 作为使用者只能再启动一个goroutine来跳出回调函数的goroutine

如果是这个问题，能否通过buffered channel或者concurrent queue把消息缓存再处理呢？类似于我之前提到的缓存消息到内存再存入redis：

```
handler goroutine1...N ----send-----> queue/channel <----recv---- worker goroutine1...M
```

**Comment by huskar-t** [comment]
如果不使用goroutine跳出而是使用channel，如果channel满了不还是会存在阻塞吗，速度还是取决于下游的处理速度，这个问题的关键是无法控制回调所在的goroutine，除了使用者再启动一个goroutine退出回调所在的goroutine，否则没有任何可靠地办法来结束回调所在的goroutine

**Comment by jeffreystoke** [comment]
> 如果不使用goroutine跳出而是使用channel，如果channel满了不还是会存在阻塞吗

channel是在存在burst的情况下适用的，而且我提了用queue，如果我只说用queue是不是还能说入队的东西太多导致oom了，不要太钻牛角尖 XD

我的理解是你想控制goroutine的数量，为了支持goroutine pool，lib内部肯定是要加消息缓存的，否则就会导致在某些情况下大幅度降低吞吐量甚至暂停接收数据，这样就会导致消息在broker堆积。这里先不论是否会oom的问题，这部分缓存的消息如果因为某种原因丢失了，qos2的消息broker不重发怎么办？是不是还得加持久化存储或者更改消息确认逻辑？

消息太多导致无法及时处理在我的理解是属于应用程序应该解决的问题，我也承认lib可以提供backpressure来缓解，但根本问题并没有得到解决，我觉得之前提到的`mqtt 消息分片，改良mqtt topic设计，实现分布式部署`更适合你的case。

**Comment by huskar-t** [comment]
我们已经处理了消息分片但是我们tps预估能达到百万级别，如果不严格控制goroutine数量会引起大面积雪崩

**Comment by jeffreystoke** [comment]
单机百万级别确实不是当初创建这个lib的目标，当时只是为了替代不顺手的paho.mqtt，目前你们是在测试阶段吗，感觉这个lib能上prod（本身都还没1.0）的希望不是很大，我还没经手过这样的项目XD

goroutine pool在百万级别肯定是必要的，但是如你所见我目前没什么时间维护这个项目，也正如之前讨论提到的，加goroutine pool涉及到很多方面，所以一时半会儿加不了，希望能够理解一下。
