### ISSUE TITLE
AsyncClient options are not accessible

### ISSUE THREAD

**Issue by jimu-liubin** [goiiot/libmqtt#35]
type AsyncClient struct {
	// Deprecated: use ConnectServer instead (will be removed in v1.0)
	servers []string
	// Deprecated: use ConnectServer instead (will be removed in v1.0)
	secureServers []string

	options          connectOptions      // client wide connection options
}

options are not accessible. When there is incoming message, I could not find a way to get incoming clientId. 

func handleTopicSubscribe(client libmqtt.Client, topic string, qos libmqtt.QosLevel, msg []byte) {
    //TODO:  how to get clientId?
}

**Comment by jeffreystoke** [comment]
Hi @jimu-liubin  these options are set by adding `libmqtt.WithXXX` (e.g. [`libmqtt.WithClientID`](https://pkg.go.dev/github.com/goiiot/libmqtt?tab=doc#WithClientID)), and they are not accessible from the package outside.

I am currently not aware of your use case but you can probably wrap the `AsyncClient` with some extra fields to identify message's client-id, or create multiple different handle funcs for each topic messages, wdyt?

**Comment by jeffreystoke** [comment]
Closing due to no further information.
