### ISSUE TITLE
failed to build the C library.

### ISSUE THREAD

**Issue by atarjoe** [goiiot/libmqtt#7]
Hi,

I've failed to build the C library on a Linux machine with the following error message:
```
env CGO_ENABLED=1 go build -buildmode=c-archive \
    -ldflags=-s -o build/libmqtt.a
# github.com/goiiot/libmqtt/c
./options_c.go:54: constant 9223372036854775807 overflows int
Makefile:31: recipe for target 'build/libmqtt.a' failed
make: *** [build/libmqtt.a] Error 2
```
The machine type is: `Linux debian 4.9.0-4-686 #1 SMP Debian 4.9.65-3 (2017-12-03) i686 GNU/Linux`

**Comment by atarjoe** [comment]
Since I've tried to build that on x86 machine it gave an error of integer overflow.
I've changed it from `math.MaxInt64` to `math.MaxInt32` and it compiled fine.

**Comment by jeffreystoke** [comment]
Sorry for the late reply, it seems a platform related issue, I will give it a look, thanks :wink:
